<a href="https://colab.research.google.com/github/chloeshin2/new2020/blob/master/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
import tensorflow as tf
import numpy as np


a = tf.constant(10)
b = tf.constant(20)

c = a+b
d = (a+b).numpy()



In [8]:
print(a)

tf.Tensor(10, shape=(), dtype=int32)


In [9]:
c 

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [10]:
type(d), d

(numpy.int32, 30)

In [11]:
#numpy ==> tensor 객체 형변환?

d2 = tf.convert_to_tensor(d)
d2

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [12]:
hello = tf.constant("Hello Tensorflow 2 World!")

hello
#문자열을 상수 로 꺼내쓸수있다?


<tf.Tensor: shape=(), dtype=string, numpy=b'Hello Tensorflow 2 World!'>

In [13]:
hello.numpy()

b'Hello Tensorflow 2 World!'

In [14]:
node1 = tf.constant(3.0, dtype = tf.float32)
node2 = tf.constant(4.0, dtype = tf.float32)
node3 = tf.add(node1, node2)
node3

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [15]:

W = tf.Variable(3.5)  #W에 임의의 값을 지정
b = tf.Variable(2.5)  #b에 임의의 값을 지정

In [16]:
#XOR 
x = np.array([[1,1],[1,0],[0,1],[0,0]])
y = np.array([[0],[1],[1],[0]])
#앤드 연산을 통해서, 

#y = ax +b 
#퍼셉트론을 중간에 넣을것인데...
# weight, bias ? as intercept

#y = W*x + b  (공식화한 함수모양)
#행렬식이라서 대문자로 한다.. 얘를 처리할 행렬도 같은 크기여야해서 대문자 처리로 행렬임을 보여준다

#선형회귀방식과 유사, 기울기와 절편을 구하는것. 

W = tf.Variable(3.5)  #W에 임의의 값을 지정
b = tf.Variable(2.5)  #b에 임의의 값을 지정

# 0 = 3.5 * 1 + 2.5
# 0 = 6 실제 값고 예측값이 안맞는것은 오차고 오차를 그래프에서 가장낮은 접점을 찾는게 머신러닝

#안맞는게 맞아요ㅋㅋ

#오차를 최소화하는게 목적 !!(***)

learning_rate = 0.01  #머신러닝 학습율

for i in range(2001):
 with tf.GradientTape() as tape:
    model = W*x +b
    cost = tf.reduce_mean(tf.square(model - y))     #줄여가는 함수 

 w1, b1 = tape.gradient(cost, [W, b])
 W.assign_sub(learning_rate*w1)
 b.assign_sub(learning_rate*b1)

 predicted = tf.cast(model>0.5, dtype = tf.float32)
 accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, y), dtype = tf.float32))

 if i%10 == 0:          #i는 횟수고 10번까지만, i값을 10으로 나눠서, 0이될때까지? 
  print( i, W.numpy(), b.numpy(), cost)

print("모델: ", model)
print("예측값:" , predicted)
print("정확도:", accuracy)
#값이 작아지면 



0 3.445 2.425 tf.Tensor(17.375, shape=(), dtype=float32)
10 2.9612508 1.7792902 tf.Tensor(10.563433, shape=(), dtype=float32)
20 2.5782466 1.2914447 tf.Tensor(6.538805, shape=(), dtype=float32)
30 2.2729619 0.9244002 tf.Tensor(4.1549273, shape=(), dtype=float32)
40 2.0277185 0.6497404 tf.Tensor(2.7374408, shape=(), dtype=float32)
50 1.8289433 0.44568062 tf.Tensor(1.8895652, shape=(), dtype=float32)
60 1.6662091 0.29552206 tf.Tensor(1.3778019, shape=(), dtype=float32)
70 1.5315033 0.18646632 tf.Tensor(1.0647178, shape=(), dtype=float32)
80 1.4186664 0.108706154 tf.Tensor(0.86939585, shape=(), dtype=float32)
90 1.3229599 0.054728232 tf.Tensor(0.7441702, shape=(), dtype=float32)
100 1.2407362 0.018778257 tf.Tensor(0.66094047, shape=(), dtype=float32)
110 1.1691846 -0.0035492354 tf.Tensor(0.60311973, shape=(), dtype=float32)
120 1.106137 -0.015625462 tf.Tensor(0.5608992, shape=(), dtype=float32)
130 1.0499185 -0.020028705 tf.Tensor(0.52846026, shape=(), dtype=float32)
140 0.99923325 -0.018

In [17]:
x.shape

(4, 2)

In [18]:
y.shape

(4, 1)

In [19]:
model = tf.keras.Sequential([
        tf.keras.layers.Dense(units=8, activation ='sigmoid', input_shape=(2,)),
        tf.keras.layers.Dense(units=1, activation = 'sigmoid')
])



In [20]:
model.compile(optimizer= tf.keras.optimizers.SGD(learning_rate=0.1), loss ="binary_crossentropy",metrics =['accuracy'])
#손실 함수의 종류도 추후에.. 정확도

In [21]:
model.fit(x,y, epochs=3000, batch_size=1)
model.summary()
model.predict(x)



스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
Epoch 154/3000
4/4 [==============================] - 0s 2ms/step - loss: 0.7258 - accuracy: 0.5000
Epoch 155/3000
4/4 [==============================] - 0s 2ms/step - loss: 0.7291 - accuracy: 0.0000e+00
Epoch 156/3000
4/4 [==============================] - 0s 2ms/step - loss: 0.7256 - accuracy: 0.5000
Epoch 157/3000
4/4 [==============================] - 0s 2ms/step - loss: 0.7255 - accuracy: 0.5000
Epoch 158/3000
4/4 [==============================] - 0s 2ms/step - loss: 0.7287 - accuracy: 0.2500
Epoch 159/3000
4/4 [==============================] - 0s 2ms/step - loss: 0.7288 - accuracy: 0.0000e+00
Epoch 160/3000
4/4 [==============================] - 0s 2ms/step - loss: 0.7286 - accuracy: 0.2500
Epoch 161/3000
4/4 [==============================] - 0s 2ms/step - loss: 0.7284 - accuracy: 0.5000
Epoch 162/3000
4/4 [==============================] - 0s 2ms/step - loss: 0.7283 - accuracy: 0.5000
Epoch 163/3000
4/4 [==============================] - 0s